version: '3.8'

services:
  test:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn test
    depends_on:
      - redis_test
    environment:
      - REDIS_URL=redis://redis_test:6379

  app:
    build: .
    ports:
      - "3445:3445"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn docker-compose-start
    depends_on:
      - test
      - redis_app
    environment:
      - REDIS_URL=redis://redis_app:6379

  redis_test:
    image: "redis:latest"
    ports:
      - "6380:6379" 
    command: redis-server --appendonly yes

  redis_app:
    image: "redis:latest"
    ports:
      - "6379:6379" 
    command: redis-server --appendonly yes
