name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main # Triggers prod deployment
      - dev # Triggers dev deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"

      - name: Install Serverless Framework
        run: yarn global add serverless

      - name: Upgrade Serverless Framework
        run: yarn global upgrade serverless

      - name: Install AWS SDK
        run: yarn add @aws-sdk/client-cloudformation

      - name: Clean Install Dependencies
        run: |
          rm -rf node_modules yarn.lock
          yarn install --frozen-lockfile

      - name: Install Serverless plugins
        run: yarn add -D serverless-plugin-typescript

      - name: Build TypeScript
        run: yarn build

      - name: Deploy to AWS Lambda (Dev)
        if: github.ref == 'refs/heads/dev'
        uses: serverless/github-action@v3
        with:
          args: deploy --stage dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to AWS Lambda (Prod)
        if: github.ref == 'refs/heads/main'
        uses: serverless/github-action@v3
        with:
          args: deploy --stage prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
